[package]
name = "site"
version = "0.1.0"
edition = "2021"
default-run = "site"
build = "build/main.rs"

[features]
dev = ["dep:notify"]

[[bin]]
name = "dev"
path = "src/bin/dev.rs"
required-features = ["dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["http1", "tokio"] }
maud = { version = "0.25.0", features = ["axum"] }
notify = { version = "8.2.0", optional = true }
tokio = { version = "1.47.1", default-features = false, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["std"] }
typst = "=0.15.1"
typst-assets = { version = "=0.15.1", features = ["fonts"] }
typst-html = "=0.15.1"
typst-kit = { version = "=0.15.1", features = ["emit-diagnostics"] }
typst-layout = "=0.15.1"
typst-pdf = "=0.15.1"
